### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by craigmulligan** [Agile-IoT/agile-data#14]
Because agile-data subscriptions run in a daemon like way, it needs a unique way to authenticate. 

Workflow:
On subscription create agile-data gets a the user token, it then creates a client on idm with the token, which contains info about the user and subscription and gets back a permanent client api key with the original users permissions? 

We then use that key to query the agile api every time the subscription runs. 

Is that ~ right? @nopbyte

**Comment by nopbyte** [comment]
Hi @craig-mulligan,

yes that is right. To clarify a bit more. The data-api needs to be extended to get an Authorization bearer token in the header with every request. In case the request should create a subscription, then the agile-data api should create a client:
To do this, the REST API can be called llike this:

```
curl -X POST -H "Content-type: application/json" -H "Authorization: bearer $TOKEN" -d '{"name":"MyAgileClient2","clientSecret":"theclientsecret", "redirectURI": "http://agilegw.local:3002/auth/example/callback"}' 'http://agilegw.local:3000/api/v1/entity/client/MyAgileClient2'
```
or the agile-sdk could be used to create an entity, passing the same body and including the id of the client and type "cllient".

Once this is successful, agile-data can store the credentials for this client, to act on behalf of a user.
Then, agile-data should obtain a token (which doesn't expire) and store it next to the client information according to this example.

https://github.com/Agile-IoT/agile-idm-examples/tree/master/client-credentials

In the end, agile-data only needs the token, but I think it would be safe to keep both, the client info and the token info for now.

**Comment by nopbyte** [comment]
I forgot to mention that the final goal of putting authentication here is to record which subscription is generated by which user, and store next to the data the device that is generated to keep ownership and provenance of the data in the data-api. We have already discussed some administrative details on Resin helping the security work package with this. I will keep moving the discussion forward in the project too...

@craig-mulligan, I would recommend we start these changes in parallel to the changes for enforcement in the agile api done by @cskiraly. Just to be able to have something by the end of August for our project delivery. Once we have this, we can merge the branch once token is flowing smoothly all the way down to the agile-api. What do you think?

**Comment by craigmulligan** [comment]
We now assign a userId with each subscription. Next we'll need to add that to every record that is created so we can enforce authentication on each document. Closing this will follow the remainder of the issue on #24
