### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by nopbyte** [Agile-IoT/agile-data#15]
We had as part of the livestock monitoring a requirement regarding encryption. 

It is phrased like this: The AGILE Gateway should support optional encryption of subject data using a specified public key, preferable using a standard asymmetrical scheme. The decryption key must not
be stored in the Gateway.

@Exulansis this also relates to the UI, since we should support the decryption of the data in the UI. So the main idea, is that the user would provide the key through the UI in order to decrypt the data and see it. As far as I can see, this would mean to have an extra field where the user could provide his key before the data is decrypted.

The part that actually encrypts would be a function call to some library like (https://www.npmjs.com/package/node-rsa). Also, storing the encryption key is solved by IDM, 

@craig-mulligan aside from the UI question,  we should also clarify whether our DB can support time series of data that is encrypted... I guess if we can store integer values in the time series, we could try to encrypt the actual value in 4 byte chunks that go to the DB which would not make too much sense when they are stored in the DB, but when they are decrypted one by one, the actual data is returned. Or otherwise, we would need some additional support just for this use case somehow.

**Comment by nopbyte** [comment]
To make encryption more efficient we could have a look at elliptic curve encryption and use an existing library there.

**Comment by Exulansis** [comment]
@nopbyte From the UI standpoint that should be no problem, probably a few things to decide one (where how and when should this happen), perhaps best clarified in a really quick call? I don't expect there to be too many issues UI wise.
The agile-data encryption support on the other hand is a little more challenging, not 100% sure how to approach that. We can do some research and discuss with @craig-mulligan, perhaps during a call as well.

**Comment by geomic** [comment]
If I understand from your email @nopbyte, we (resin) wouldn't be looking to implement code specific to Pilot-B (as we have no involvement) but rather agile-data additions to support DB encryption through security?

I'm discussing (also) this with @craig-mulligan and we'll involve Andreas from our sec team, but can we bring in the relevant party from Pilot-B to this thread please? We could do with a summary of requirements, any existing code that shows how data is collected which I can't find (and what data.. as you pointed out we need to know if timeseries, or other, and level of encryption available for the DB used) to see how we can "hook" these data with the data service to persist it in an encrypted manner (and without much overhead given we're still taking about a Pi)...

**Comment by craigmulligan** [comment]
Hey @Exulansis @nopbyte, Yea we definitely need to discuss this. Let organise a call next week?

**Comment by nopbyte** [comment]
Hi @geomic,

Yes. This would be a contribution to the security WP, not to the pilots. However, one of the drone pilots asked for this:

PΒ_SC_1:  The AGILE Gateway should support optional encryption of subject data using a specified public key, preferable using a standard asymmetrical scheme. The decryption key must not be stored in the Gateway. 

PΒ_SC_2: The AGILE Gateway should preferably support enabling/disabling of encryption per attribute, so that some parameters might be viewable directly from the AGILE gateway and others need the decryption key for access.

A more complete definition of the use case is in Section 3.3.8 of D8.1

Some scenarios may require that data is kept safe from any outside intruders in case the AGILE gateway is captured either on ground or after a UAV crash/shootdown. Even though the AGILE gateway should require users (internet, local) to login before data access, this may not be good enough if the data is still readable from memory. It would be preferable that the AGILE gateway can be optionally supplied with a public key to be used for data encryption. The decryption key (private key) must not be stored in the gateway but only be available to end-users of the data. In this way, sensor data is encrypted and then locally stored, so that data will be safe from any intruder attack.

The specific encryption technology to use is TBD, but it should be a standardized scheme. If the security option is checked, the private key must be supplied to the AGILE gateway before data can be viewed from e.g. a web interface. This key must always reside in RAM and only as long as the user session lasts.
Preferable it should be possible to select encryption per attribute, so that some parameters might be viewable directly from the AGILE gateway and others need the private key for access.

@Exulansis @craig-mulligan  I am available for a call this week. Maybe we could do this after the virtual table since we are there already?

I will try to contact the people from the Pilot over email, since I don't know their github usernames...

**Comment by mojtaba-esk** [comment]
Hi everybody, I happily just joined FBK as a security researcher. Cryptography is not my main specialty, I am familiar with it.

@nopbyte  I suggest that to store the private key only in the end-user's device and use a browser plugin to decrypt the data locally without requiring transferring the key to the gateway.

However, there is a risk of data availability in case of losing the user's private key which can be mitigated by storing it in another place encrypted by user's password as a key or use a hardware backup key.

Another risk is that if the user's private key gets compromised all her previous data can be decrypted by an attacker, there is a technique for it called "forward secrecy". However, I am not sure if it can be used in a asymmetric scheme or not. I need to double check it.

To improve the security, we should also generate key pairs periodically or even multiple keys. For this solution, we need to use a hierarchy key generation mechanism.

At the end, we need a comprehensive key management system for Agile.

I'll come back to you again and will be happy to hear from you about it.

**Comment by nopbyte** [comment]
hi @mojtaba-esk,

Nice to meet you, and welcome to AGILE! 

I understand your point about never placing the private key on the gateway. At the moment the UI runs in the browser, so if the decryption happens in the UI instead of the agile-data component this would not require a plugin (even better for adoption). To do this, we could move the decryption part to the agile-sdk.

However, although this is theoretically the best solution, we have to be careful and  consider  practical aspects in the project too:

* The pilots want to leverage the data visualilzation provided by the Gateway software stack, and in its current implementation, the ui gets information from agile-data and renders it. So, if we decrypt inside agile-data there are less changes to the current components. Also, to favour integration of security I assume developers may find it easier if agile-data supports encryption directly (available through HTTP), instead of requiring agile-data and the agile-sdk (javascript only) .

* Aside from arguments to increase adoption of security, and making our life easier to implement this in the current software stack, we also have to consider that security in agile covers many other aspects, such as usage control within the gateway, and potentially outsourcing of queries over encrypted data externally (we are looking at  ZeroDB or CryptDB), we have to be careful to allocate resources for development where needed. And we have many fronts to cover in the Work Package.

I hope we get more input on how integration would happen with Pilots soon (I circulated the link to this issue within the Pilot work package)  to be able to move the discussion forward and define the best course of action.

**Comment by mojtaba-esk** [comment]
Thank you @nopbyte Nice to meet you too. 

and thanks for the detailed and clarifying comments.
Visualilzation on gateway raises another challenge which leads us to choose a point in the trade-off vector of usability and security. 
If Agile supports HTTPS then we can protect the transmission of data between the user, gateway, fog and cloud. I need to get more familiar with Agile details and that link would be useful to check.
cheers

**Comment by kdo-sw** [comment]
@nopbyte:

Yes, we definitely envisioned the encryption functionality encapsulated inside the local storage/agile-data component when we originally defined the requirements in D8.1. As long as the decryption key is persistent in memory only, that will be sufficient security for our use.

Sky-Watch is no expert in encryption/security and open for the actual technology used for this. 

We envisioned a simple API for exchanging private/public keys as part of the API for local storage. Public keys would be automatically stored and remembered by the local storage component whereas private keys would have to be supplied for each new session. For actual implementation we do not care if the encryption happens on the entire table/database or on specified binary rows in a table as described by @nopbyte. Maybe even technology like the deprecated TrueCrypt could be utilised?

**Comment by nopbyte** [comment]
Hi @kdo-sw,
Thanks for your input. 
Today, @geomic and @Exulansis  were mentioning that there is a chance that the Gateway is not planned to fly with the drone, and collect information to its internal database, in your use case. I thought that the gateway was flying with the drone?. 
If the gateway is not with the drone, what are you using to collect the data in the drone?

**Comment by kdo-sw** [comment]
The Gateway will indeed be mounted in the drone. It is correct that we in D8.1 wanted a backup option to place the Gateway with the ground station due to a concern that it would be too heavy to carry as payload (see D8.1, Table 26, Pilot B Risk Summary). However in D8.2 we clarified that it would definitely be carried on-board the UAV.

**Comment by geomic** [comment]
We started a discussion here also: https://docs.google.com/document/d/1KCaGjIHpLM8SQQa3JL4TiyBQnfmoqWJFsyy1YFCj-TA/edit?usp=sharing and will update this issue as we have a more concrete specification nailed.
