### ISSUE TITLE
Test early implementation

### ISSUE THREAD

**Issue by geomic** [Agile-IoT/agile-data#9]
@Exulansis cheers for confirming testing this. I'm opening a discussion here in case @craig-mulligan has any specific test-cases that he would like you to go through. Will let you discuss.

**Comment by craigmulligan** [comment]
@Exulansis, have you had any issue so far. If you are interested I added agile.data.* methods to the sdk, you can see them used in agile-data's tests. 

Let me know if you hit any issues.
